<?php

namespace LogisticsBundle\Repository;

/**
 * CatalogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogItemRepository extends \Doctrine\ORM\EntityRepository
{
}
