<?php

namespace LogisticsBundle\Repository;

/**
 * CatalogPackDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogPackDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
