<?php

namespace LogisticsBundle\Repository;

/**
 * ErroredOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErroredOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
