<?php

namespace LogisticsBundle\Repository;

/**
 * InventoryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
